[package]
name = "lights"
version = "0.1.0"
edition = "2021"

[dependencies]
render = { path = "../render" }
math = {path = "../math"}
pollster = "0.3"
bytemuck = { version = "1.14", features = [ "derive" ] }
cgmath = "0.18"
wgpu = "0.18"
